### ISSUE TITLE
pluginbody.asciidoc does not properly exclude examples (input example appears in codec)

### ISSUE THREAD

**Issue by shendaras** [elasticsearch/logstash-docs#42]
I haven't spent a lot of time understanding the machinery by how the pages are generated, but here is an example:
http://www.elasticsearch.org/guide/en/logstash/current/_how_to_write_a_logstash_codec_plugin.html

Under the section "see what your plugin looks like", you see two code examples.  The first, which is guarded in the asciidoc by an ifdef::run_method[] ... endif block, appears.  The codec example follows just after.  The code example still inherits the pluginname and plugintype attributes among others, so the input example actually shows an inheritance from Logstash::Codecs::Base which is unfortunate.

**Comment by untergeek** [comment]
Thanks for catching this.  Our document generation is multiphase and we missed this.  The ifdef segments work in plain asciidoc, but our format bundles everything into one doc, so those variables are effectively in each successive page, hence the successive rendering of blocks.

I am working to rectify this right now.
